export interface ComposerInfo {
  nombre: string;
  vida: string;
  nacionalidad: string;
  bio: string;
  estilo: string;
  portrait: string; // path a /images/composers/
  color: string;    // color acento para el retrato
}

export const composers: Record<string, ComposerInfo> = {
  "Johann Sebastian Bach": {
    nombre: "Johann Sebastian Bach",
    vida: "1685 – 1750",
    nacionalidad: "Alemán",
    bio: "Considerado el mayor compositor del período barroco y uno de los más influyentes de la historia de la música occidental. Bach dominó todas las formas musicales de su época con una profundidad intelectual y espiritual sin igual. Su obra para teclado —preludios, fugas, invenciones y suites— sigue siendo el fundamento del estudio pianístico moderno.",
    estilo: "Barroco · Contrapunto · Polifonía",
    portrait: "/images/composers/bach.jpg",
    color: "#C9A84C",
  },
  "Georg Friedrich Händel": {
    nombre: "Georg Friedrich Händel",
    vida: "1685 – 1759",
    nacionalidad: "Alemán-Británico",
    bio: "Contemporáneo de Bach, Händel desarrolló su carrera principalmente en Inglaterra y se convirtió en uno de los maestros del Barroco internacional. Aunque célebre por sus oratorios, su música para teclado muestra una elegancia y accesibilidad características de su estilo cosmopolita.",
    estilo: "Barroco · Elegancia melódica",
    portrait: "/images/composers/handel.jpg",
    color: "#A08040",
  },
  "Domenico Scarlatti": {
    nombre: "Domenico Scarlatti",
    vida: "1685 – 1757",
    nacionalidad: "Italiano",
    bio: "Virtuoso del clavicémbalo que pasó gran parte de su vida en la corte española. Sus 555 sonatas para teclado son obras maestras de ingenio, con cruzamientos de manos, saltos atrevidos y ritmos ibéricos únicos que anticiparon el estilo pianístico del futuro.",
    estilo: "Barroco tardío · Virtuosismo · Influencia española",
    portrait: "/images/composers/scarlatti.svg",
    color: "#B87A30",
  },
  "Joseph Haydn": {
    nombre: "Joseph Haydn",
    vida: "1732 – 1809",
    nacionalidad: "Austriaco",
    bio: "Llamado el 'Padre de la Sinfonía', Haydn fue el arquitecto del estilo clásico. Pasó casi treinta años al servicio de la familia Esterházy, componiendo con disciplina y humor. Sus sonatas para piano, llenas de sorpresas e ingenio, fueron clave en la evolución del instrumento.",
    estilo: "Clásico · Forma sonata · Humor musical",
    portrait: "/images/composers/haydn.jpg",
    color: "#7090B0",
  },
  "Wolfgang A. Mozart": {
    nombre: "Wolfgang Amadeus Mozart",
    vida: "1756 – 1791",
    nacionalidad: "Austriaco",
    bio: "Niño prodigio que se convirtió en símbolo de la perfección clásica. Mozart escribió más de 20 sonatas para piano, numerosas fantasías y una serie de conciertos que siguen siendo cumbres del repertorio. Su música combina profundidad emocional con una claridad formal que parece sin esfuerzo.",
    estilo: "Clásico · Gracia melódica · Arquitectura formal",
    portrait: "/images/composers/mozart.jpg",
    color: "#6080C0",
  },
  "Ludwig van Beethoven": {
    nombre: "Ludwig van Beethoven",
    vida: "1770 – 1827",
    nacionalidad: "Alemán",
    bio: "El puente entre el Clasicismo y el Romanticismo. A pesar de perder la audición progresivamente, Beethoven compuso algunas de las obras más poderosas de la historia, incluidas 32 sonatas para piano que exploran todo el rango expresivo del instrumento. Su lucha personal se convirtió en arte universal.",
    estilo: "Clásico-Romántico · Drama · Innovación formal",
    portrait: "/images/composers/beethoven.jpg",
    color: "#8060A0",
  },
  "Franz Schubert": {
    nombre: "Franz Schubert",
    vida: "1797 – 1828",
    nacionalidad: "Austriaco",
    bio: "En tan solo 31 años, Schubert creó un catálogo extraordinario que incluye sonatas, impromptus y momentos musicales de belleza lírica inigualable. Su música para piano está impregnada de una melancolía vienesa que anticipa el Romanticismo tardío con una espontaneidad única.",
    estilo: "Romántico temprano · Lirismo · Melancolía",
    portrait: "/images/composers/schubert.jpg",
    color: "#5090A0",
  },
  "Frédéric Chopin": {
    nombre: "Frédéric Chopin",
    vida: "1810 – 1849",
    nacionalidad: "Polaco-Francés",
    bio: "El poeta del piano por excelencia. Chopin dedicó casi toda su obra al instrumento, creando nocturnos, estudios, preludios y baladas que redefinen el lirismo pianístico. Vivió gran parte de su vida en París, donde su salón fue el epicentro de la vida musical romántica.",
    estilo: "Romántico · Bel canto pianístico · Ornamentación",
    portrait: "/images/composers/chopin.jpg",
    color: "#9060A0",
  },
  "Robert Schumann": {
    nombre: "Robert Schumann",
    vida: "1810 – 1856",
    nacionalidad: "Alemán",
    bio: "Compositor, pianista y crítico musical, Schumann es una de las figuras más complejas del Romanticismo. Sus ciclos para piano —Carnaval, Escenas infantiles, Kreisleriana— son retratos íntimos de personajes y estados de ánimo, con una originalidad armónica que influyó profundamente en la música posterior.",
    estilo: "Romántico · Ciclos programáticos · Introspección",
    portrait: "/images/composers/schumann.jpg",
    color: "#A07040",
  },
  "Franz Liszt": {
    nombre: "Franz Liszt",
    vida: "1811 – 1886",
    nacionalidad: "Húngaro",
    bio: "El pianista más virtuoso de su época, Liszt revolucionó la técnica pianística y creó el concepto del recital moderno. Su música va desde estudios de trascendencia extrema hasta páginas de profunda espiritualidad, pasando por las evocadoras Rapsodias Húngaras que capturan el alma de su pueblo.",
    estilo: "Romántico · Virtuosismo extremo · Programa musical",
    portrait: "/images/composers/liszt.jpg",
    color: "#C06040",
  },
  "Johannes Brahms": {
    nombre: "Johannes Brahms",
    vida: "1833 – 1897",
    nacionalidad: "Alemán",
    bio: "Brahms fue el guardián de la forma clásica en la era romántica. Su música para piano, densa y meditativa, une la rigurosa arquitectura de Bach y Beethoven con el lirismo de su propio tiempo. Sus intermezzi tardíos son conversaciones íntimas de incomparable profundidad.",
    estilo: "Romántico · Rigor formal · Densidad armónica",
    portrait: "/images/composers/brahms.jpg",
    color: "#806050",
  },
  "Edvard Grieg": {
    nombre: "Edvard Grieg",
    vida: "1843 – 1907",
    nacionalidad: "Noruego",
    bio: "El gran representante del nacionalismo musical escandinavo. Las Piezas Líricas de Grieg —66 miniaturas para piano en diez volúmenes— son instantáneas poéticas de paisajes, danzas y estados de ánimo nórdicos. Su Concierto para piano en La menor es uno de los más populares del repertorio.",
    estilo: "Romántico tardío · Nacionalismo nórdico · Miniaturismo",
    portrait: "/images/composers/grieg.jpg",
    color: "#408080",
  },
  "Piotr I. Tchaikovsky": {
    nombre: "Piotr Ilich Tchaikovsky",
    vida: "1840 – 1893",
    nacionalidad: "Ruso",
    bio: "El compositor ruso más internacional del siglo XIX. Aunque célebre por sus ballets y sinfonías, Tchaikovsky escribió ciclos pianísticos de gran encanto melódico. Las Estaciones, doce piezas que evocan los meses del año, son su obra más popular para piano.",
    estilo: "Romántico · Melodismo ruso · Orquestación colorística",
    portrait: "/images/composers/tchaikovsky.jpg",
    color: "#5060A0",
  },
  "Erik Satie": {
    nombre: "Erik Satie",
    vida: "1866 – 1925",
    nacionalidad: "Francés",
    bio: "Excéntrico y visionario, Satie fue uno de los compositores más originales de su tiempo. Sus Gymnopédies y Gnossiennes anticiparon el minimalismo y la música ambiente con décadas de adelanto. Despojó a la música de todo ornamento superfluo, creando un mundo sonoro propio, silencioso y contemplativo.",
    estilo: "Moderno temprano · Minimalismo · Humor dadaísta",
    portrait: "/images/composers/satie.jpg",
    color: "#608040",
  },
  "Claude Debussy": {
    nombre: "Claude Debussy",
    vida: "1862 – 1918",
    nacionalidad: "Francés",
    bio: "Fundador del impresionismo musical, Debussy transformó el lenguaje armónico de la música occidental. Su piano es un instrumento de luz y color: escalas de tonos enteros, acordes en paralelo y texturas etéreas crean paisajes sonoros de extraordinaria belleza. Clair de Lune es una de las páginas más amadas de la música clásica.",
    estilo: "Impresionismo · Simbolismo · Timbre como forma",
    portrait: "/images/composers/debussy.jpg",
    color: "#4080A0",
  },
  "Maurice Ravel": {
    nombre: "Maurice Ravel",
    vida: "1875 – 1937",
    nacionalidad: "Francés",
    bio: "A menudo asociado al impresionismo de Debussy, Ravel fue en realidad un maestro del clasicismo moderno con una precisión de relojero suizo. Su música para piano combina rigor formal, exotismo y una orquestación imaginaria que hace del instrumento una pequeña orquesta.",
    estilo: "Moderno · Neobarroco · Precisión artesanal",
    portrait: "/images/composers/ravel.svg",
    color: "#60A080",
  },
  "Scott Joplin": {
    nombre: "Scott Joplin",
    vida: "1868 – 1917",
    nacionalidad: "Estadounidense",
    bio: "El 'Rey del Ragtime', Joplin elevó la música popular afroamericana a la categoría de arte. Sus rags —Maple Leaf Rag, The Entertainer, Elite Syncopations— combinan ritmos sincopados irresistibles con una elegancia formal que los distingue de la música de baile ordinaria. Pionero ignorado en vida, hoy es símbolo del patrimonio musical americano.",
    estilo: "Ragtime · Jazz temprano · Sincopación",
    portrait: "/images/composers/joplin.jpg",
    color: "#C08040",
  },
  "Béla Bartók": {
    nombre: "Béla Bartók",
    vida: "1881 – 1945",
    nacionalidad: "Húngaro",
    bio: "Etnomusicólogo y compositor vanguardista, Bartók fusionó las tradiciones folclóricas de Hungría, Rumanía y Bulgaria con el lenguaje moderno. Su Mikrokosmos —153 piezas progresivas— es una de las colecciones pedagógicas más importantes del siglo XX, llevando al piano desde lo más simple hasta lo más complejo.",
    estilo: "Moderno · Folclore · Politonalidad",
    portrait: "/images/composers/bartok.jpg",
    color: "#A04040",
  },
  "Sergei Prokofiev": {
    nombre: "Sergei Prokofiev",
    vida: "1891 – 1953",
    nacionalidad: "Ruso",
    bio: "Pianista virtuoso y compositor iconoclasta, Prokofiev renovó el lenguaje pianístico con su característica combinación de sarcasmo, lirismo y percusividad. Sus nueve sonatas para piano son obras monumentales del repertorio del siglo XX.",
    estilo: "Moderno · Neoclásico · Percusividad",
    portrait: "/images/composers/prokofiev.svg",
    color: "#804040",
  },
  // ── NUEVOS COMPOSITORES (info compacta sin bio completa) ─────────
  "Carl Philipp Emanuel Bach": {
    nombre: "Carl Philipp Emanuel Bach", vida: "1714 – 1788", nacionalidad: "Alemán",
    bio: "Segundo hijo de J.S. Bach y puente entre el Barroco y el Clasicismo. Su Ensayo sobre la verdadera manera de tocar instrumentos de teclado fue el manual de referencia del siglo XVIII.",
    estilo: "Pre-clásico · Empfindsamer Stil", portrait: "/images/composers/bach_cpe.svg", color: "#B89440",
  },
  "François Couperin": {
    nombre: "François Couperin", vida: "1668 – 1733", nacionalidad: "Francés",
    bio: "Maestro del clavicémbalo francés, 'Couperin le Grand' compuso 234 piezas para teclado agrupadas en ordres, miniaturas evocadoras con títulos pintorescos que anticipan la música programática.",
    estilo: "Barroco francés · Ornamentación refinada", portrait: "/images/composers/couperin.svg", color: "#A89040",
  },
  "Jean-Philippe Rameau": {
    nombre: "Jean-Philippe Rameau", vida: "1683 – 1764", nacionalidad: "Francés",
    bio: "Compositor y teórico musical cuyo Traité de l'harmonie (1722) sigue siendo fundamento del análisis armónico. Sus piezas para clavicémbalo son pequeñas joyas de dibujo melódico y rítmico.",
    estilo: "Barroco francés · Teoría armónica", portrait: "/images/composers/rameau.svg", color: "#C09048",
  },
  "Georg Philipp Telemann": {
    nombre: "Georg Philipp Telemann", vida: "1681 – 1767", nacionalidad: "Alemán",
    bio: "Uno de los compositores más prolíficos de la historia, admirado en su tiempo por encima de Bach. Su música para teclado es práctica, elegante y muy didáctica.",
    estilo: "Barroco tardío · Estilo galante", portrait: "/images/composers/telemann.svg", color: "#B08838",
  },
  "Henry Purcell": {
    nombre: "Henry Purcell", vida: "1658 – 1695", nacionalidad: "Inglés",
    bio: "El mayor compositor inglés del Barroco. Su música para teclado combina la tradición inglesa con influencias francesas e italianas en un estilo único de sobria belleza.",
    estilo: "Barroco inglés · Armonía audaz", portrait: "/images/composers/purcell.svg", color: "#A07838",
  },
  "Dieterich Buxtehude": {
    nombre: "Dieterich Buxtehude", vida: "c.1637 – 1707", nacionalidad: "Alemán-Danés",
    bio: "Organista de Lübeck cuya fama atrajo a un joven Bach a caminar 400 km para escucharle. Sus obras de teclado unen el virtuosismo norteño con una profunda expresividad espiritual.",
    estilo: "Barroco norteño · Fantasía libre", portrait: "/images/composers/buxtehude.svg", color: "#988038",
  },
  "Johann Pachelbel": {
    nombre: "Johann Pachelbel", vida: "1653 – 1706", nacionalidad: "Alemán",
    bio: "Conocido mundialmente por su Canon en Re, Pachelbel fue un pilar de la música para órgano y teclado del sur de Alemania. Sus corales influyeron directamente en Bach.",
    estilo: "Barroco medio · Contrapunto claro", portrait: "/images/composers/pachelbel.svg", color: "#A88030",
  },
  "Johann J. Froberger": {
    nombre: "Johann Jakob Froberger", vida: "1616 – 1667", nacionalidad: "Alemán",
    bio: "Pionero de la suite de teclado, Froberger sintetizó los estilos italiano, francés y alemán. Sus laments y tombeaux son piezas programáticas de profunda expresividad.",
    estilo: "Barroco medio · Suite de teclado", portrait: "/images/composers/froberger.svg", color: "#A88840",
  },
  "Johann Kuhnau": {
    nombre: "Johann Kuhnau", vida: "1660 – 1722", nacionalidad: "Alemán",
    bio: "Antecesor de Bach en Leipzig, Kuhnau fue pionero de la música programática para teclado con sus Sonatas Bíblicas, que ilustran escenas del Antiguo Testamento.",
    estilo: "Barroco · Música programática", portrait: "/images/composers/kuhnau.svg", color: "#B08830",
  },
  "Arcangelo Corelli": {
    nombre: "Arcangelo Corelli", vida: "1653 – 1713", nacionalidad: "Italiano",
    bio: "Padre del estilo barroco italiano. Aunque famoso por sus sonatas de violín, sus obras sentaron las bases tonales y formales del teclado posterior.",
    estilo: "Barroco italiano · Arquitectura tonal", portrait: "/images/composers/corelli.svg", color: "#C09838",
  },
  "Antonio Vivaldi": {
    nombre: "Antonio Vivaldi", vida: "1678 – 1741", nacionalidad: "Italiano",
    bio: "El 'Cura Rojo' revolucionó el concierto barroco. Aunque principalmente violinista, muchas de sus obras se transcriben con éxito al piano para uso pedagógico.",
    estilo: "Barroco italiano · Virtuosismo violinístico", portrait: "/images/composers/vivaldi.svg", color: "#B09830",
  },
  "Muzio Clementi": {
    nombre: "Muzio Clementi", vida: "1752 – 1832", nacionalidad: "Italiano-Británico",
    bio: "Conocido como 'el padre del piano', Clementi fue rival virtuosístico de Mozart y maestro de Field y Cramer. Su Gradus ad Parnassum es uno de los métodos pianísticos más influyentes.",
    estilo: "Clásico · Virtuosismo pianístico", portrait: "/images/composers/clementi.svg", color: "#708090",
  },
  "Friedrich Kuhlau": {
    nombre: "Friedrich Kuhlau", vida: "1786 – 1832", nacionalidad: "Danés-Alemán",
    bio: "Las sonatinas de Kuhlau son un pilar de la educación pianística moderna. Accesibles y musicalmente ricas, acompañan a los estudiantes en sus primeros pasos en la forma sonata.",
    estilo: "Clásico-Romántico · Didáctica", portrait: "/images/composers/kuhlau.svg", color: "#607890",
  },
  "Jan L. Dussek": {
    nombre: "Jan Ladislav Dussek", vida: "1760 – 1812", nacionalidad: "Bohemio",
    bio: "Virtuoso del piano forte y compositor visionario que anticipó muchos rasgos del Romanticismo. Fue el primer pianista en tocar con el instrumento en perfil hacia el público.",
    estilo: "Clásico-Romántico · Innovación pianística", portrait: "/images/composers/dussek.svg", color: "#5878A0",
  },
  "Anton Diabelli": {
    nombre: "Anton Diabelli", vida: "1781 – 1858", nacionalidad: "Austriaco",
    bio: "Editor y compositor vienés, inmortalizado por Beethoven en sus monumentales Variaciones Diabelli sobre un tema que el propio Diabelli había enviado como encargo.",
    estilo: "Clásico-Romántico · Música de salón", portrait: "/images/composers/diabelli.svg", color: "#7088B0",
  },
  "Carl Czerny": {
    nombre: "Carl Czerny", vida: "1791 – 1857", nacionalidad: "Austriaco",
    bio: "Alumno de Beethoven y maestro de Liszt. Compuso más de mil obras, muchas pedagógicas — sus estudios siguen siendo ejercicio obligado para todo pianista en formación.",
    estilo: "Clásico-Romántico · Técnica pianística", portrait: "/images/composers/czerny.svg", color: "#6878A0",
  },
  "Felix Mendelssohn": {
    nombre: "Felix Mendelssohn-Bartholdy", vida: "1809 – 1847", nacionalidad: "Alemán",
    bio: "Niño prodigio y figura central del Romanticismo temprano. Sus Romanzas sin palabras crearon un género que marcó la pequeña forma pianística del siglo XIX.",
    estilo: "Romántico temprano · Elegancia clásica", portrait: "/images/composers/mendelssohn.svg", color: "#6090A0",
  },
  "John Field": {
    nombre: "John Field", vida: "1782 – 1837", nacionalidad: "Irlandés",
    bio: "Inventor del nocturno pianístico, forma que Chopin llevaría a su máxima expresión. Field introdujo la textura de melodía cantabile sobre acompañamiento ondulante que definió el género.",
    estilo: "Romántico temprano · Nocturno", portrait: "/images/composers/field.svg", color: "#6080A0",
  },
  "Charles-Valentin Alkan": {
    nombre: "Charles-Valentin Alkan", vida: "1813 – 1888", nacionalidad: "Francés",
    bio: "Amigo de Chopin y Liszt, Alkan escribió algunas de las obras más difíciles del repertorio. Su excentricidad lo relegó al olvido hasta su redescubrimiento en el siglo XX.",
    estilo: "Romántico · Virtuosismo extremo", portrait: "/images/composers/alkan.svg", color: "#B07060",
  },
  "Johann F. F. Burgmüller": {
    nombre: "Johann Friedrich Franz Burgmüller", vida: "1806 – 1874", nacionalidad: "Alemán",
    bio: "Sus 25 Estudios Op.100 son un tesoro pedagógico: cada estudio aborda una dificultad técnica específica envuelta en una miniatura musical de gran encanto.",
    estilo: "Romántico · Didáctica progresiva", portrait: "/images/composers/burgmuller.svg", color: "#908060",
  },
  "Gabriel Fauré": {
    nombre: "Gabriel Fauré", vida: "1845 – 1924", nacionalidad: "Francés",
    bio: "Puente entre el Romanticismo y el siglo XX, Fauré creó un lenguaje armónico propio, sutil y perfumado. Sus trece nocturnos y cuatro valses-caprichos son joyas del piano francés.",
    estilo: "Romántico tardío · Armonía modal", portrait: "/images/composers/faure.svg", color: "#509090",
  },
  "César Franck": {
    nombre: "César Franck", vida: "1822 – 1890", nacionalidad: "Belga-Francés",
    bio: "Tardío en reconocerse como compositor, Franck renovó la música francesa con su uso de la forma cíclica. Su Preludio, Coral y Fuga es cumbre del piano romántico.",
    estilo: "Romántico · Forma cíclica · Cromatismo", portrait: "/images/composers/franck.svg", color: "#607080",
  },
  "Camille Saint-Saëns": {
    nombre: "Camille Saint-Saëns", vida: "1835 – 1921", nacionalidad: "Francés",
    bio: "Niño prodigio, virtuoso del piano y el órgano, Saint-Saëns fue una figura central de la música francesa durante siete décadas. Sus cinco conciertos para piano son pilares del repertorio.",
    estilo: "Romántico · Claridad francesa", portrait: "/images/composers/saint_saens.svg", color: "#708080",
  },
  "Isaac Albéniz": {
    nombre: "Isaac Albéniz", vida: "1860 – 1909", nacionalidad: "Español",
    bio: "Su suite Iberia es la obra pianística española más importante y uno de los grandes ciclos del piano del siglo XX. Albéniz tradujo al piano toda la riqueza sonora de Andalucía.",
    estilo: "Nacionalismo español · Impresionismo", portrait: "/images/composers/albeniz.svg", color: "#B07840",
  },
  "Antonín Dvořák": {
    nombre: "Antonín Dvořák", vida: "1841 – 1904", nacionalidad: "Checo",
    bio: "Junto a Smetana, figura máxima del nacionalismo checo. Sus Humoresques para piano contienen la célebre N.º7, una de las melodías más reconocibles del siglo XIX.",
    estilo: "Nacionalismo checo · Folclore eslavo", portrait: "/images/composers/dvorak.svg", color: "#608070",
  },
  "Modest Músorgski": {
    nombre: "Modest Músorgski", vida: "1839 – 1881", nacionalidad: "Ruso",
    bio: "Miembro del Grupo de los Cinco, creador del realismo ruso en música. Sus Cuadros de una exposición son una de las obras más imaginativas del repertorio pianístico.",
    estilo: "Nacionalismo ruso · Realismo musical", portrait: "/images/composers/mussorgsky.svg", color: "#905040",
  },
  "Nikolái Rimski-Kórsakov": {
    nombre: "Nikolái Rimski-Kórsakov", vida: "1844 – 1908", nacionalidad: "Ruso",
    bio: "Maestro de la orquestación y figura clave del Grupo de los Cinco. Su música para piano, menos conocida, muestra el mismo refinamiento colorístico de sus sinfonías.",
    estilo: "Nacionalismo ruso · Colorismo orquestal", portrait: "/images/composers/rimsky_korsakov.svg", color: "#7080A0",
  },
  "Sergei Rachmaninoff": {
    nombre: "Sergei Rachmaninoff", vida: "1873 – 1943", nacionalidad: "Ruso",
    bio: "Último gran pianista-compositor en la tradición romántica. Sus preludios, estudios-cuadros y conciertos para piano combinan melancolía eslava con un virtuosismo trascendental.",
    estilo: "Romántico tardío · Virtuosismo ruso", portrait: "/images/composers/rachmaninoff.svg", color: "#5060A0",
  },
  "Alexander Scriabin": {
    nombre: "Alexander Scriabin", vida: "1872 – 1915", nacionalidad: "Ruso",
    bio: "Visionario y místico, Scriabin evolucionó desde Chopin hasta un lenguaje armónico propio basado en el 'acorde místico'. Sus últimas sonatas son cumbres del modernismo.",
    estilo: "Romántico-Místico · Armonía post-tonal", portrait: "/images/composers/scriabin.svg", color: "#A05090",
  },
  "Paul Dukas": {
    nombre: "Paul Dukas", vida: "1865 – 1935", nacionalidad: "Francés",
    bio: "Aunque conocido mundialmente por El aprendiz de brujo, Dukas compuso una importante sonata para piano (1901), obra monumental y culminación de la tradición francesa romántica.",
    estilo: "Post-romántico francés · Orquestación", portrait: "/images/composers/dukas.svg", color: "#708060",
  },
  "Niccolò Paganini": {
    nombre: "Niccolò Paganini", vida: "1782 – 1840", nacionalidad: "Italiano",
    bio: "El violinista más legendario de la historia. Sus 24 Caprichos inspiraron transcripciones pianísticas de Liszt, Schumann, Brahms y Rachmaninoff.",
    estilo: "Romántico · Virtuosismo violinístico", portrait: "/images/composers/paganini.svg", color: "#A04030",
  },
  "Johann Strauss (hijo)": {
    nombre: "Johann Strauss (hijo)", vida: "1825 – 1899", nacionalidad: "Austriaco",
    bio: "El 'Rey del Vals' vienés. Aunque sus obras maestras son orquestales, las transcripciones pianísticas de sus valses son éxito seguro en el salón.",
    estilo: "Romántico · Vals vienés", portrait: "/images/composers/strauss_jj.svg", color: "#A08060",
  },
};

// Descripciones para piezas conocidas por nombre de archivo
export const pieceDescriptions: Record<string, string> = {
  "moonlight": "La Sonata Op.27 N.º2 debe su apodo a una descripción poética del crítico Ludwig Rellstab. El primer movimiento, con sus célebres tresillos sobre un bajo ostinato, es una de las páginas más reconocibles de toda la música clásica.",
  "pathetique-1": "El primer movimiento de la Sonata 'Patética' Op.13 abre con una introducción lenta de carácter dramático. Beethoven la dedicó al Príncipe Lichnowsky y fue una de sus primeras obras en recibir un título programático.",
  "pathetique-2": "El Adagio cantabile de la Sonata Patética es uno de los movimientos lentos más sublimes de Beethoven. Su melodía, de carácter vocal, contrasta con la intensidad del primer movimiento.",
  "pathetique-3": "El Rondó final de la Patética retoma el carácter dramático con una energía rítmica característica, cerrando el ciclo con brillantez y determinación.",
  "wtk1-prelude1": "El Preludio en Do Mayor que abre el Clave Bien Temperado es quizás la pieza más célebre de Bach. Sobre sus arpegios, Gounod compuso más tarde su famosa Ave María.",
  "wtk1-fugue1": "La Fuga en Do Mayor del primer libro del Clave Bien Temperado muestra la maestría contrapuntística de Bach en su forma más pura: cuatro voces tejidas con perfecta lógica y expresividad.",
  "fur-elise": "Für Elise (Para Elisa) fue descubierta cuarenta años después de la muerte de Beethoven. La identidad de la destinataria sigue siendo un misterio. Su melodía inicial de cinco notas es probablemente la más reconocida del mundo.",
  "gymnopedie-1": "La primera Gymnopédie (1888) lleva una indicación poco usual: 'Lento et douloureux' (lento y doloroso). Su ritmo de vals ralentizado y sus armonías inusuales crean un estado de melancolía suspendida.",
  "gnossienne-1": "Satie escribió las Gnossiennes sin compás ni barras de tiempo, indicando solo 'Ne sortez pas' (No salgas). El resultado es una música que parece flotar fuera del tiempo.",
  "rom_folk_dance_1_bartok": "Esta danza folclórica rumana es una de las miniaturas más accesibles de Bartók, resultado de sus investigaciones etnomusicológicas por los Balcanes. Muestra cómo el folclore puede integrarse en un lenguaje pianístico moderno.",
};
