export interface ComposerInfo {
  nombre: string;
  vida: string;
  nacionalidad: string;
  bio: string;
  estilo: string;
  portrait: string; // path a /images/composers/
  color: string;    // color acento para el retrato
}

export const composers: Record<string, ComposerInfo> = {
  "Johann Sebastian Bach": {
    nombre: "Johann Sebastian Bach",
    vida: "1685 – 1750",
    nacionalidad: "Alemán",
    bio: "Considerado el mayor compositor del período barroco y uno de los más influyentes de la historia de la música occidental. Bach dominó todas las formas musicales de su época con una profundidad intelectual y espiritual sin igual. Su obra para teclado —preludios, fugas, invenciones y suites— sigue siendo el fundamento del estudio pianístico moderno.",
    estilo: "Barroco · Contrapunto · Polifonía",
    portrait: "/images/composers/bach.jpg",
    color: "#C9A84C",
  },
  "Georg Friedrich Händel": {
    nombre: "Georg Friedrich Händel",
    vida: "1685 – 1759",
    nacionalidad: "Alemán-Británico",
    bio: "Contemporáneo de Bach, Händel desarrolló su carrera principalmente en Inglaterra y se convirtió en uno de los maestros del Barroco internacional. Aunque célebre por sus oratorios, su música para teclado muestra una elegancia y accesibilidad características de su estilo cosmopolita.",
    estilo: "Barroco · Elegancia melódica",
    portrait: "/images/composers/handel.jpg",
    color: "#A08040",
  },
  "Domenico Scarlatti": {
    nombre: "Domenico Scarlatti",
    vida: "1685 – 1757",
    nacionalidad: "Italiano",
    bio: "Virtuoso del clavicémbalo que pasó gran parte de su vida en la corte española. Sus 555 sonatas para teclado son obras maestras de ingenio, con cruzamientos de manos, saltos atrevidos y ritmos ibéricos únicos que anticiparon el estilo pianístico del futuro.",
    estilo: "Barroco tardío · Virtuosismo · Influencia española",
    portrait: "/images/composers/scarlatti.svg",
    color: "#B87A30",
  },
  "Joseph Haydn": {
    nombre: "Joseph Haydn",
    vida: "1732 – 1809",
    nacionalidad: "Austriaco",
    bio: "Llamado el 'Padre de la Sinfonía', Haydn fue el arquitecto del estilo clásico. Pasó casi treinta años al servicio de la familia Esterházy, componiendo con disciplina y humor. Sus sonatas para piano, llenas de sorpresas e ingenio, fueron clave en la evolución del instrumento.",
    estilo: "Clásico · Forma sonata · Humor musical",
    portrait: "/images/composers/haydn.jpg",
    color: "#7090B0",
  },
  "Wolfgang A. Mozart": {
    nombre: "Wolfgang Amadeus Mozart",
    vida: "1756 – 1791",
    nacionalidad: "Austriaco",
    bio: "Niño prodigio que se convirtió en símbolo de la perfección clásica. Mozart escribió más de 20 sonatas para piano, numerosas fantasías y una serie de conciertos que siguen siendo cumbres del repertorio. Su música combina profundidad emocional con una claridad formal que parece sin esfuerzo.",
    estilo: "Clásico · Gracia melódica · Arquitectura formal",
    portrait: "/images/composers/mozart.jpg",
    color: "#6080C0",
  },
  "Ludwig van Beethoven": {
    nombre: "Ludwig van Beethoven",
    vida: "1770 – 1827",
    nacionalidad: "Alemán",
    bio: "El puente entre el Clasicismo y el Romanticismo. A pesar de perder la audición progresivamente, Beethoven compuso algunas de las obras más poderosas de la historia, incluidas 32 sonatas para piano que exploran todo el rango expresivo del instrumento. Su lucha personal se convirtió en arte universal.",
    estilo: "Clásico-Romántico · Drama · Innovación formal",
    portrait: "/images/composers/beethoven.jpg",
    color: "#8060A0",
  },
  "Franz Schubert": {
    nombre: "Franz Schubert",
    vida: "1797 – 1828",
    nacionalidad: "Austriaco",
    bio: "En tan solo 31 años, Schubert creó un catálogo extraordinario que incluye sonatas, impromptus y momentos musicales de belleza lírica inigualable. Su música para piano está impregnada de una melancolía vienesa que anticipa el Romanticismo tardío con una espontaneidad única.",
    estilo: "Romántico temprano · Lirismo · Melancolía",
    portrait: "/images/composers/schubert.jpg",
    color: "#5090A0",
  },
  "Frédéric Chopin": {
    nombre: "Frédéric Chopin",
    vida: "1810 – 1849",
    nacionalidad: "Polaco-Francés",
    bio: "El poeta del piano por excelencia. Chopin dedicó casi toda su obra al instrumento, creando nocturnos, estudios, preludios y baladas que redefinen el lirismo pianístico. Vivió gran parte de su vida en París, donde su salón fue el epicentro de la vida musical romántica.",
    estilo: "Romántico · Bel canto pianístico · Ornamentación",
    portrait: "/images/composers/chopin.jpg",
    color: "#9060A0",
  },
  "Robert Schumann": {
    nombre: "Robert Schumann",
    vida: "1810 – 1856",
    nacionalidad: "Alemán",
    bio: "Compositor, pianista y crítico musical, Schumann es una de las figuras más complejas del Romanticismo. Sus ciclos para piano —Carnaval, Escenas infantiles, Kreisleriana— son retratos íntimos de personajes y estados de ánimo, con una originalidad armónica que influyó profundamente en la música posterior.",
    estilo: "Romántico · Ciclos programáticos · Introspección",
    portrait: "/images/composers/schumann.jpg",
    color: "#A07040",
  },
  "Franz Liszt": {
    nombre: "Franz Liszt",
    vida: "1811 – 1886",
    nacionalidad: "Húngaro",
    bio: "El pianista más virtuoso de su época, Liszt revolucionó la técnica pianística y creó el concepto del recital moderno. Su música va desde estudios de trascendencia extrema hasta páginas de profunda espiritualidad, pasando por las evocadoras Rapsodias Húngaras que capturan el alma de su pueblo.",
    estilo: "Romántico · Virtuosismo extremo · Programa musical",
    portrait: "/images/composers/liszt.jpg",
    color: "#C06040",
  },
  "Johannes Brahms": {
    nombre: "Johannes Brahms",
    vida: "1833 – 1897",
    nacionalidad: "Alemán",
    bio: "Brahms fue el guardián de la forma clásica en la era romántica. Su música para piano, densa y meditativa, une la rigurosa arquitectura de Bach y Beethoven con el lirismo de su propio tiempo. Sus intermezzi tardíos son conversaciones íntimas de incomparable profundidad.",
    estilo: "Romántico · Rigor formal · Densidad armónica",
    portrait: "/images/composers/brahms.jpg",
    color: "#806050",
  },
  "Edvard Grieg": {
    nombre: "Edvard Grieg",
    vida: "1843 – 1907",
    nacionalidad: "Noruego",
    bio: "El gran representante del nacionalismo musical escandinavo. Las Piezas Líricas de Grieg —66 miniaturas para piano en diez volúmenes— son instantáneas poéticas de paisajes, danzas y estados de ánimo nórdicos. Su Concierto para piano en La menor es uno de los más populares del repertorio.",
    estilo: "Romántico tardío · Nacionalismo nórdico · Miniaturismo",
    portrait: "/images/composers/grieg.jpg",
    color: "#408080",
  },
  "Piotr I. Tchaikovsky": {
    nombre: "Piotr Ilich Tchaikovsky",
    vida: "1840 – 1893",
    nacionalidad: "Ruso",
    bio: "El compositor ruso más internacional del siglo XIX. Aunque célebre por sus ballets y sinfonías, Tchaikovsky escribió ciclos pianísticos de gran encanto melódico. Las Estaciones, doce piezas que evocan los meses del año, son su obra más popular para piano.",
    estilo: "Romántico · Melodismo ruso · Orquestación colorística",
    portrait: "/images/composers/tchaikovsky.jpg",
    color: "#5060A0",
  },
  "Erik Satie": {
    nombre: "Erik Satie",
    vida: "1866 – 1925",
    nacionalidad: "Francés",
    bio: "Excéntrico y visionario, Satie fue uno de los compositores más originales de su tiempo. Sus Gymnopédies y Gnossiennes anticiparon el minimalismo y la música ambiente con décadas de adelanto. Despojó a la música de todo ornamento superfluo, creando un mundo sonoro propio, silencioso y contemplativo.",
    estilo: "Moderno temprano · Minimalismo · Humor dadaísta",
    portrait: "/images/composers/satie.jpg",
    color: "#608040",
  },
  "Claude Debussy": {
    nombre: "Claude Debussy",
    vida: "1862 – 1918",
    nacionalidad: "Francés",
    bio: "Fundador del impresionismo musical, Debussy transformó el lenguaje armónico de la música occidental. Su piano es un instrumento de luz y color: escalas de tonos enteros, acordes en paralelo y texturas etéreas crean paisajes sonoros de extraordinaria belleza. Clair de Lune es una de las páginas más amadas de la música clásica.",
    estilo: "Impresionismo · Simbolismo · Timbre como forma",
    portrait: "/images/composers/debussy.jpg",
    color: "#4080A0",
  },
  "Maurice Ravel": {
    nombre: "Maurice Ravel",
    vida: "1875 – 1937",
    nacionalidad: "Francés",
    bio: "A menudo asociado al impresionismo de Debussy, Ravel fue en realidad un maestro del clasicismo moderno con una precisión de relojero suizo. Su música para piano combina rigor formal, exotismo y una orquestación imaginaria que hace del instrumento una pequeña orquesta.",
    estilo: "Moderno · Neobarroco · Precisión artesanal",
    portrait: "/images/composers/ravel.svg",
    color: "#60A080",
  },
  "Scott Joplin": {
    nombre: "Scott Joplin",
    vida: "1868 – 1917",
    nacionalidad: "Estadounidense",
    bio: "El 'Rey del Ragtime', Joplin elevó la música popular afroamericana a la categoría de arte. Sus rags —Maple Leaf Rag, The Entertainer, Elite Syncopations— combinan ritmos sincopados irresistibles con una elegancia formal que los distingue de la música de baile ordinaria. Pionero ignorado en vida, hoy es símbolo del patrimonio musical americano.",
    estilo: "Ragtime · Jazz temprano · Sincopación",
    portrait: "/images/composers/joplin.jpg",
    color: "#C08040",
  },
  "Béla Bartók": {
    nombre: "Béla Bartók",
    vida: "1881 – 1945",
    nacionalidad: "Húngaro",
    bio: "Etnomusicólogo y compositor vanguardista, Bartók fusionó las tradiciones folclóricas de Hungría, Rumanía y Bulgaria con el lenguaje moderno. Su Mikrokosmos —153 piezas progresivas— es una de las colecciones pedagógicas más importantes del siglo XX, llevando al piano desde lo más simple hasta lo más complejo.",
    estilo: "Moderno · Folclore · Politonalidad",
    portrait: "/images/composers/bartok.jpg",
    color: "#A04040",
  },
  "Sergei Prokofiev": {
    nombre: "Sergei Prokofiev",
    vida: "1891 – 1953",
    nacionalidad: "Ruso",
    bio: "Pianista virtuoso y compositor iconoclasta, Prokofiev renovó el lenguaje pianístico con su característica combinación de sarcasmo, lirismo y percusividad. Sus nueve sonatas para piano son obras monumentales del repertorio del siglo XX.",
    estilo: "Moderno · Neoclásico · Percusividad",
    portrait: "/images/composers/prokofiev.svg",
    color: "#804040",
  },
};

// Descripciones para piezas conocidas por nombre de archivo
export const pieceDescriptions: Record<string, string> = {
  "moonlight": "La Sonata Op.27 N.º2 debe su apodo a una descripción poética del crítico Ludwig Rellstab. El primer movimiento, con sus célebres tresillos sobre un bajo ostinato, es una de las páginas más reconocibles de toda la música clásica.",
  "pathetique-1": "El primer movimiento de la Sonata 'Patética' Op.13 abre con una introducción lenta de carácter dramático. Beethoven la dedicó al Príncipe Lichnowsky y fue una de sus primeras obras en recibir un título programático.",
  "pathetique-2": "El Adagio cantabile de la Sonata Patética es uno de los movimientos lentos más sublimes de Beethoven. Su melodía, de carácter vocal, contrasta con la intensidad del primer movimiento.",
  "pathetique-3": "El Rondó final de la Patética retoma el carácter dramático con una energía rítmica característica, cerrando el ciclo con brillantez y determinación.",
  "wtk1-prelude1": "El Preludio en Do Mayor que abre el Clave Bien Temperado es quizás la pieza más célebre de Bach. Sobre sus arpegios, Gounod compuso más tarde su famosa Ave María.",
  "wtk1-fugue1": "La Fuga en Do Mayor del primer libro del Clave Bien Temperado muestra la maestría contrapuntística de Bach en su forma más pura: cuatro voces tejidas con perfecta lógica y expresividad.",
  "fur-elise": "Für Elise (Para Elisa) fue descubierta cuarenta años después de la muerte de Beethoven. La identidad de la destinataria sigue siendo un misterio. Su melodía inicial de cinco notas es probablemente la más reconocida del mundo.",
  "gymnopedie-1": "La primera Gymnopédie (1888) lleva una indicación poco usual: 'Lento et douloureux' (lento y doloroso). Su ritmo de vals ralentizado y sus armonías inusuales crean un estado de melancolía suspendida.",
  "gnossienne-1": "Satie escribió las Gnossiennes sin compás ni barras de tiempo, indicando solo 'Ne sortez pas' (No salgas). El resultado es una música que parece flotar fuera del tiempo.",
  "rom_folk_dance_1_bartok": "Esta danza folclórica rumana es una de las miniaturas más accesibles de Bartók, resultado de sus investigaciones etnomusicológicas por los Balcanes. Muestra cómo el folclore puede integrarse en un lenguaje pianístico moderno.",
};
