export interface MarcaPiano {
  id:           string;
  nombre:       string;
  fundacion:    number;
  cese?:        number;
  pais:         string;
  ciudad:       string;
  fundador:     string;
  lema:         string;
  historia:     string;
  innovaciones: string[];
  usuarios:     string[];
  webOficial?:  string;
  color:        string;
  acento:       string;
  emblema:      string; // path SVG
}

export const marcas: MarcaPiano[] = [
  {
    id: "steinway",
    nombre: "Steinway & Sons",
    fundacion: 1853,
    pais: "EE.UU. / Alemania",
    ciudad: "Nueva York · Hamburgo",
    fundador: "Heinrich Engelhard Steinweg",
    lema: "The Instrument of the Immortals",
    historia: "Fundada por el luthier alemán Heinrich Engelhard Steinweg en Nueva York, Steinway revolucionó la fabricación de pianos con más de 125 patentes técnicas. La casa es hoy el referente absoluto del piano de concierto: el 97% de los solistas que actúan con orquestas sinfónicas elige un Steinway. Su fábrica de Queens y la hermana de Hamburgo siguen fabricando cada piano a mano con las mismas técnicas del siglo XIX.",
    innovaciones: [
      "Tabla armónica de abeto curvada con prensa hidráulica (1860)",
      "Cruzado completo de cuerdas (1859)",
      "Marco de hierro de una sola pieza",
      "Acción de repetición Capo d'Astro",
    ],
    usuarios: ["Arthur Rubinstein", "Vladimir Horowitz", "Glenn Gould", "Lang Lang", "Daniil Trifonov"],
    webOficial: "https://www.steinway.com",
    color: "#8B6914",
    acento: "#D4AF37",
    emblema: "/images/marcas/steinway.svg",
  },
  {
    id: "bosendorfer",
    nombre: "Bösendorfer",
    fundacion: 1828,
    pais: "Austria",
    ciudad: "Viena",
    fundador: "Ignaz Bösendorfer",
    lema: "The Tone of Vienna",
    historia: "La casa más antigua del mundo entre las grandes marcas de piano sigue en activo. Bösendorfer se hizo famosa cuando el joven Franz Liszt, que destruía cualquier piano con su virtuosismo extremo, declaró en 1828 que el Bösendorfer de Ignaz había sobrevivido a uno de sus recitales más brutales. Su modelo Imperial Concert Grand (290 cm) es único por sus 97 teclas (9 graves adicionales) que confieren al instrumento una resonancia inconfundible.",
    innovaciones: [
      "Piano Imperial de 97 teclas (modelo 290)",
      "Tabla armónica construida como un instrumento tradicional vienés",
      "Proceso de fabricación de 62 semanas por piano",
      "Sistema de afinación exclusivo Single-String",
    ],
    usuarios: ["Franz Liszt", "Leonard Bernstein", "Oscar Peterson", "Tori Amos"],
    webOficial: "https://www.boesendorfer.com",
    color: "#6B2C0B",
    acento: "#B8560C",
    emblema: "/images/marcas/bosendorfer.svg",
  },
  {
    id: "bechstein",
    nombre: "C. Bechstein",
    fundacion: 1853,
    pais: "Alemania",
    ciudad: "Berlín",
    fundador: "Carl Bechstein",
    lema: "Since 1853 · The sound of Europe",
    historia: "Fundada el mismo año que Steinway, Bechstein fue durante décadas el piano preferido de la realeza y aristocracia europea. Su sonido más cálido y lírico, con un ataque menos agresivo que el Steinway, lo convirtió en el favorito de Debussy, quien lo describía como el instrumento ideal para su música. Tras difíciles décadas en el siglo XX, la casa fue reflotada y hoy sus modelos D 282 y M/P son referentes del concierto europeo.",
    innovaciones: [
      "Primera acción moderna para repetición rápida (1866)",
      "Bechstein Concert Services con 100+ pianos de concierto en alquiler",
      "Tecnología Vario: piano de cola convertible a digital silencioso",
      "Bechstein Digital con sampling propio",
    ],
    usuarios: ["Claude Debussy", "Wilhelm Furtwängler", "Jorge Bolet", "Arthur Schnabel"],
    webOficial: "https://www.bechstein.com",
    color: "#2B3A55",
    acento: "#5D7AAD",
    emblema: "/images/marcas/bechstein.svg",
  },
  {
    id: "bluthner",
    nombre: "Blüthner",
    fundacion: 1853,
    pais: "Alemania",
    ciudad: "Leipzig",
    fundador: "Julius Blüthner",
    lema: "The Golden Tone",
    historia: "Fabricante saxón fundado en Leipzig, cuna de Bach y Mendelssohn. Blüthner es célebre por su patente del Aliquot Stringing: una cuarta cuerda simpática que vibra por resonancia en el registro agudo, creando el característico 'Golden Tone' (tono dorado) con armónicos extraordinariamente ricos. Fue el piano elegido por los Beatles para sus grabaciones de Abbey Road y por el Titanic para su salón de primera clase.",
    innovaciones: [
      "Aliquot Stringing: cuarta cuerda simpática (1873)",
      "Proceso de secado de maderas 5-10 años",
      "Fabricación artesanal en Leipzig desde 1853",
      "Piano vertical Lucid Hybrid con control digital",
    ],
    usuarios: ["Béla Bartók", "The Beatles", "Elton John", "Arthur Rubinstein"],
    webOficial: "https://www.bluethner.com",
    color: "#7A5919",
    acento: "#C89B3B",
    emblema: "/images/marcas/bluthner.svg",
  },
  {
    id: "fazioli",
    nombre: "Fazioli",
    fundacion: 1981,
    pais: "Italia",
    ciudad: "Sacile",
    fundador: "Paolo Fazioli",
    lema: "La perfección italiana",
    historia: "La casa italiana más joven entre las grandes, fundada por el ingeniero y pianista Paolo Fazioli con la ambición explícita de crear el mejor piano de concierto del mundo. Cada instrumento se fabrica artesanalmente con madera de abeto del Val di Fiemme — el mismo bosque que Stradivari usaba para sus violines. Con apenas 140 pianos al año, Fazioli es sinónimo de exclusividad. Su modelo F308 (308 cm) es el piano de cola más grande producido en serie.",
    innovaciones: [
      "Piano de cola F308: 308 cm, el más largo del mundo",
      "Cuarto pedal que reduce el desplazamiento del martillo",
      "Madera de abeto del Val di Fiemme (misma que Stradivari)",
      "Producción limitada a ~140 pianos/año",
    ],
    usuarios: ["Angela Hewitt", "Herbie Hancock", "Aldo Ciccolini", "Paul Lewis"],
    webOficial: "https://www.fazioli.com",
    color: "#5B2A1E",
    acento: "#B85438",
    emblema: "/images/marcas/fazioli.svg",
  },
  {
    id: "yamaha",
    nombre: "Yamaha",
    fundacion: 1887,
    pais: "Japón",
    ciudad: "Hamamatsu",
    fundador: "Torakusu Yamaha",
    lema: "Artist Services · Made for Music",
    historia: "El mayor fabricante de pianos del mundo, Yamaha comenzó en 1887 cuando Torakusu Yamaha reparó un armonio occidental y decidió construir uno propio. En el siglo XX, Yamaha democratizó el acceso al piano de calidad con producción industrial de precisión japonesa. Su serie CFX de concierto compite al máximo nivel, mientras que la serie Disklavier integró playback MIDI en pianos acústicos reales — un hito tecnológico. Hoy produce ~100.000 pianos anuales.",
    innovaciones: [
      "Disklavier: piano acústico con reproducción MIDI (1986)",
      "Silent Piano: modo silencioso con auriculares",
      "Piano híbrido AvantGrand con mecánica acústica + sonido digital",
      "Serie CFX usada por ganadores del Concurso Chopin",
    ],
    usuarios: ["Sviatoslav Richter", "Chick Corea", "Elton John", "Billy Joel"],
    webOficial: "https://www.yamaha.com",
    color: "#3D2A5A",
    acento: "#8064B8",
    emblema: "/images/marcas/yamaha.svg",
  },
  {
    id: "kawai",
    nombre: "Kawai",
    fundacion: 1927,
    pais: "Japón",
    ciudad: "Hamamatsu",
    fundador: "Koichi Kawai",
    lema: "The Future of the Piano",
    historia: "Fundada por Koichi Kawai, antiguo ingeniero de Yamaha que se independizó para diseñar pianos según su propia visión. Kawai es pionera en el uso de materiales compuestos (fibra de carbono ABS) en las piezas móviles del mecanismo, logrando mayor durabilidad y estabilidad climática que la madera tradicional. Su serie Shigeru Kawai representa lo más alto de la marca, con instrumentos de concierto revisados personalmente por 'maestros piano artesanos' en Japón.",
    innovaciones: [
      "Materiales compuestos ABS-Carbón en la acción (1980s)",
      "Serie Shigeru Kawai con certificación Master Piano Artisan",
      "Sistema Millenium III de acción ultra-rápida",
      "Tabla armónica Duplex Scale extendida",
    ],
    usuarios: ["Martha Argerich", "Shigeru Kawai", "Andre Watts"],
    webOficial: "https://www.kawai-global.com",
    color: "#1F3A5C",
    acento: "#4E82BA",
    emblema: "/images/marcas/kawai.svg",
  },
  {
    id: "pleyel",
    nombre: "Pleyel",
    fundacion: 1807,
    cese: 2013,
    pais: "Francia",
    ciudad: "París",
    fundador: "Ignace Pleyel",
    lema: "Le piano de Chopin",
    historia: "Fundada por el compositor austro-francés Ignace Pleyel, discípulo de Haydn, la casa Pleyel fue durante el siglo XIX la gran rival de Érard en París. Chopin era su devoto absoluto y dio su último concierto público en la Salle Pleyel (1848). Los pianos Pleyel del período romántico tenían una acción ligera y un sonido más íntimo y cantabile, considerados por Chopin 'el ideal para la música de salón'. Tras 200 años, la fábrica cerró en 2013, pero la marca sigue activa con instrumentos digitales.",
    innovaciones: [
      "Primer piano vertical moderno en Europa (1826)",
      "Mecánica ligera ideal para el repertorio romántico",
      "Diseño estético art-déco en el siglo XX",
      "Piano pleyel-cushing con forma curva anatómica",
    ],
    usuarios: ["Frédéric Chopin", "Igor Stravinsky", "Maurice Ravel", "Edith Piaf"],
    webOficial: "https://www.pleyel.fr",
    color: "#4A1B3D",
    acento: "#9B3F7C",
    emblema: "/images/marcas/pleyel.svg",
  },
  {
    id: "erard",
    nombre: "Érard",
    fundacion: 1780,
    cese: 1960,
    pais: "Francia",
    ciudad: "París",
    fundador: "Sébastien Érard",
    lema: "L'innovation française",
    historia: "La casa más histórica de la pianística francesa. Sébastien Érard fue uno de los mayores inventores del piano moderno: en 1821 patentó la acción de doble escape, que permite la repetición rápida de una misma nota — tecnología que sigue siendo la base de todos los pianos de cola actuales. Érard fue el piano de Liszt, Mendelssohn, Ravel y Fauré. La fábrica cerró definitivamente en 1960, pero sus instrumentos históricos siguen siendo los más codiciados por los intérpretes de música romántica en instrumentos originales.",
    innovaciones: [
      "Acción de doble escape (1821) — base de todos los pianos modernos",
      "Primer piano de cola con marco de hierro (1825)",
      "Arpa moderna de doble acción",
      "Técnicas de construcción imitadas por toda la industria",
    ],
    usuarios: ["Franz Liszt", "Felix Mendelssohn", "Maurice Ravel", "Gabriel Fauré"],
    color: "#3A2818",
    acento: "#8B6A45",
    emblema: "/images/marcas/erard.svg",
  },
  {
    id: "baldwin",
    nombre: "Baldwin",
    fundacion: 1862,
    pais: "Estados Unidos",
    ciudad: "Cincinnati",
    fundador: "Dwight Hamilton Baldwin",
    lema: "America's Piano",
    historia: "Gigante americano fundado en Cincinnati por Dwight Hamilton Baldwin, que pasó de vender pianos Steinway a fabricar los suyos propios. Durante el siglo XX, Baldwin se convirtió en el piano oficial de la Casa Blanca y fue elegido por pianistas como Earl Wild, Leonard Bernstein (su Baldwin personal está en el Smithsonian) y Liberace. La marca aún produce pianos en China bajo propiedad de Gibson Brands.",
    innovaciones: [
      "Sistema de cuerdas paralelas Accu-just",
      "Piano oficial de la Casa Blanca durante décadas",
      "Serie Artist con diseño de concierto americano",
      "Integración vertical: todas las piezas fabricadas in-house",
    ],
    usuarios: ["Leonard Bernstein", "Earl Wild", "Liberace", "Dave Brubeck"],
    webOficial: "https://www.baldwinpiano.com",
    color: "#4B2C0B",
    acento: "#A0632E",
    emblema: "/images/marcas/baldwin.svg",
  },
];
