export type Periodo = "Barroco" | "Clásico" | "Romántico" | "Moderno";
export type Nivel   = "Principiante" | "Intermedio" | "Avanzado";

export interface Partitura {
  id: string;
  titulo: string;
  compositor: string;
  periodo: Periodo;
  nivel: Nivel;
  dificultad: 1 | 2 | 3 | 4 | 5;
  descripcion: string;
  imslpUrl: string;
  anio: string;
}

export const partituras: Partitura[] = [
  // ── BARROCO ──────────────────────────────────────
  {
    id: "bach-preludio-do",
    titulo: "Preludio en Do Mayor (WTC I)",
    compositor: "Johann Sebastian Bach",
    periodo: "Barroco",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "Uno de los preludios más conocidos de Bach. Ideal para iniciarse en el contrapunto barroco.",
    imslpUrl: "https://imslp.org/wiki/The_Well-Tempered_Clavier,_Book_1_(Bach,_Johann_Sebastian)",
    anio: "1722",
  },
  {
    id: "bach-minueto-sol",
    titulo: "Minueto en Sol Mayor (BWV Anh. 114)",
    compositor: "Johann Sebastian Bach",
    periodo: "Barroco",
    nivel: "Principiante",
    dificultad: 1,
    descripcion: "Pieza esencial para estudiantes. Elegante y breve, perfecta para aprender fraseo barroco.",
    imslpUrl: "https://imslp.org/wiki/Notebook_for_Anna_Magdalena_Bach_(Bach,_Johann_Sebastian)",
    anio: "1725",
  },
  {
    id: "bach-invencion-1",
    titulo: "Invención a 2 voces N.º 1 (BWV 772)",
    compositor: "Johann Sebastian Bach",
    periodo: "Barroco",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Las invenciones desarrollan la independencia de manos y el pensamiento polifónico.",
    imslpUrl: "https://imslp.org/wiki/Inventions,_BWV_772-786_(Bach,_Johann_Sebastian)",
    anio: "1723",
  },
  {
    id: "handel-aire",
    titulo: "Aire en Re menor (HWV 461)",
    compositor: "Georg Friedrich Händel",
    periodo: "Barroco",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "Melodía expresiva y sencilla que transmite toda la elegancia del período barroco.",
    imslpUrl: "https://imslp.org/wiki/Keyboard_Suite_in_D_minor,_HWV_447_(Handel,_George_Frideric)",
    anio: "1720",
  },

  // ── CLÁSICO ───────────────────────────────────────
  {
    id: "mozart-sonata-k545",
    titulo: "Sonata en Do Mayor K. 545",
    compositor: "Wolfgang Amadeus Mozart",
    periodo: "Clásico",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "Compuesta para principiantes, es hoy una de las obras más interpretadas de Mozart.",
    imslpUrl: "https://imslp.org/wiki/Piano_Sonata_No.16,_K.545_(Mozart,_Wolfgang_Amadeus)",
    anio: "1788",
  },
  {
    id: "mozart-sonata-k331",
    titulo: "Sonata K. 331 — Alla Turca",
    compositor: "Wolfgang Amadeus Mozart",
    periodo: "Clásico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "El famoso tercer movimiento 'Alla Turca' es uno de los fragmentos más reconocibles del piano clásico.",
    imslpUrl: "https://imslp.org/wiki/Piano_Sonata_No.11,_K.331/300i_(Mozart,_Wolfgang_Amadeus)",
    anio: "1783",
  },
  {
    id: "beethoven-fur-elise",
    titulo: "Für Elise (WoO 59)",
    compositor: "Ludwig van Beethoven",
    periodo: "Clásico",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "La pieza más popular de Beethoven. Su melodía característica la hace reconocible en todo el mundo.",
    imslpUrl: "https://imslp.org/wiki/Für_Elise,_WoO_59_(Beethoven,_Ludwig_van)",
    anio: "1810",
  },
  {
    id: "beethoven-claro-luna",
    titulo: "Sonata 'Claro de Luna' Op. 27 N.º 2",
    compositor: "Ludwig van Beethoven",
    periodo: "Clásico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "El primer movimiento con sus arpegios de tresillos es una de las páginas más evocadoras del piano.",
    imslpUrl: "https://imslp.org/wiki/Piano_Sonata_No.14,_Op.27_No.2_(Beethoven,_Ludwig_van)",
    anio: "1801",
  },
  {
    id: "beethoven-oda-alegria",
    titulo: "Oda a la Alegría (arreglo piano)",
    compositor: "Ludwig van Beethoven",
    periodo: "Clásico",
    nivel: "Principiante",
    dificultad: 1,
    descripcion: "Arreglo sencillo del tema final de la Novena Sinfonía. Ideal para comenzar.",
    imslpUrl: "https://imslp.org/wiki/Symphony_No.9,_Op.125_(Beethoven,_Ludwig_van)",
    anio: "1824",
  },
  {
    id: "haydn-sonata-16",
    titulo: "Sonata en Do Mayor Hob. XVI/1",
    compositor: "Joseph Haydn",
    periodo: "Clásico",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "Una de las sonatas más accesibles de Haydn, con un carácter alegre y vivaz.",
    imslpUrl: "https://imslp.org/wiki/Piano_Sonata_in_C_major,_Hob.XVI/1_(Haydn,_Joseph)",
    anio: "1760",
  },

  // ── ROMÁNTICO ─────────────────────────────────────
  {
    id: "chopin-nocturno-op9-2",
    titulo: "Nocturno Op. 9 N.º 2 en Mi♭ Mayor",
    compositor: "Frédéric Chopin",
    periodo: "Romántico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Melodía cantabile sobre un acompañamiento ondulante. El nocturno más famoso de Chopin.",
    imslpUrl: "https://imslp.org/wiki/Nocturnes,_Op.9_(Chopin,_Frédéric)",
    anio: "1832",
  },
  {
    id: "chopin-preludio-gota",
    titulo: "Preludio Op. 28 N.º 15 'La gota de lluvia'",
    compositor: "Frédéric Chopin",
    periodo: "Romántico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "La nota repetida imita la lluvia en Mallorca. Uno de los 24 preludios más interpretados.",
    imslpUrl: "https://imslp.org/wiki/Preludes,_Op.28_(Chopin,_Frédéric)",
    anio: "1839",
  },
  {
    id: "chopin-vals-op64-2",
    titulo: "Vals Op. 64 N.º 2 en Do# menor",
    compositor: "Frédéric Chopin",
    periodo: "Romántico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Vals melancólico con un carácter introspectivo, de los últimos que compuso Chopin.",
    imslpUrl: "https://imslp.org/wiki/Waltzes,_Op.64_(Chopin,_Frédéric)",
    anio: "1847",
  },
  {
    id: "schubert-momento-musical",
    titulo: "Momento Musical Op. 94 N.º 3",
    compositor: "Franz Schubert",
    periodo: "Romántico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Pieza lírica de gran expresividad. Un ejemplo del estilo íntimo y personal de Schubert.",
    imslpUrl: "https://imslp.org/wiki/6_Moments_musicaux,_Op.94_(Schubert,_Franz)",
    anio: "1828",
  },
  {
    id: "schumann-traumerei",
    titulo: "Träumerei (Escenas infantiles Op. 15)",
    compositor: "Robert Schumann",
    periodo: "Romántico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Soñadora y profunda, Träumerei es una de las miniaturas más hermosas del Romanticismo.",
    imslpUrl: "https://imslp.org/wiki/Kinderszenen,_Op.15_(Schumann,_Robert)",
    anio: "1838",
  },
  {
    id: "liszt-consolation-3",
    titulo: "Consolación N.º 3 en Re♭ Mayor",
    compositor: "Franz Liszt",
    periodo: "Romántico",
    nivel: "Avanzado",
    dificultad: 4,
    descripcion: "La más célebre de las seis Consolaciones. Canto de paz y serenidad de gran profundidad.",
    imslpUrl: "https://imslp.org/wiki/Consolations,_S.172_(Liszt,_Franz)",
    anio: "1850",
  },
  {
    id: "brahms-intermezzo-118",
    titulo: "Intermezzo Op. 118 N.º 2 en La Mayor",
    compositor: "Johannes Brahms",
    periodo: "Romántico",
    nivel: "Avanzado",
    dificultad: 4,
    descripcion: "Una de las obras más queridas de Brahms. Melancolía y ternura en perfecta proporción.",
    imslpUrl: "https://imslp.org/wiki/6_Piano_Pieces,_Op.118_(Brahms,_Johannes)",
    anio: "1893",
  },
  {
    id: "grieg-pieza-lirica",
    titulo: "Pieza lírica 'A la primavera' Op. 43 N.º 6",
    compositor: "Edvard Grieg",
    periodo: "Romántico",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "El carácter nórdico de Grieg brilla en esta evocadora pieza llena de frescura.",
    imslpUrl: "https://imslp.org/wiki/Lyric_Pieces,_Op.43_(Grieg,_Edvard)",
    anio: "1886",
  },

  // ── MODERNO ───────────────────────────────────────
  {
    id: "satie-gymnopedie-1",
    titulo: "Gymnopédie N.º 1",
    compositor: "Erik Satie",
    periodo: "Moderno",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "Pieza minimalista de tempo lento. Su atmósfera meditativa la hace perfecta para relajarse.",
    imslpUrl: "https://imslp.org/wiki/3_Gymnopédies_(Satie,_Erik)",
    anio: "1888",
  },
  {
    id: "satie-gnossienne-1",
    titulo: "Gnossienne N.º 1",
    compositor: "Erik Satie",
    periodo: "Moderno",
    nivel: "Principiante",
    dificultad: 2,
    descripcion: "Sin compás ni barras de tiempo, esta pieza explora un mundo sonoro íntimo y misterioso.",
    imslpUrl: "https://imslp.org/wiki/3_Gnossiennes_(Satie,_Erik)",
    anio: "1893",
  },
  {
    id: "debussy-clair-lune",
    titulo: "Clair de Lune (Suite Bergamasque)",
    compositor: "Claude Debussy",
    periodo: "Moderno",
    nivel: "Avanzado",
    dificultad: 4,
    descripcion: "La obra más popular de Debussy. Sus arpegios etéreos evocan la luz de la luna sobre el agua.",
    imslpUrl: "https://imslp.org/wiki/Suite_bergamasque_(Debussy,_Claude)",
    anio: "1905",
  },
  {
    id: "debussy-arabesque-1",
    titulo: "Arabesca N.º 1 en Mi Mayor",
    compositor: "Claude Debussy",
    periodo: "Moderno",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Fluida y ornamental, esta arabesca es una joya del impresionismo pianístico.",
    imslpUrl: "https://imslp.org/wiki/2_Arabesques_(Debussy,_Claude)",
    anio: "1891",
  },
  {
    id: "ravel-pavane",
    titulo: "Pavane pour une infante défunte",
    compositor: "Maurice Ravel",
    periodo: "Moderno",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "Evocación de una danza pausada y melancólica. Una de las obras más bellas del piano francés.",
    imslpUrl: "https://imslp.org/wiki/Pavane_pour_une_infante_défunte_(Ravel,_Maurice)",
    anio: "1899",
  },
  {
    id: "joplin-maple-leaf",
    titulo: "Maple Leaf Rag",
    compositor: "Scott Joplin",
    periodo: "Moderno",
    nivel: "Intermedio",
    dificultad: 3,
    descripcion: "El ragtime más famoso de la historia. Ritmo sincopado y alegría desbordante.",
    imslpUrl: "https://imslp.org/wiki/Maple_Leaf_Rag_(Joplin,_Scott)",
    anio: "1899",
  },
  {
    id: "bartok-mikrokosmos",
    titulo: "Mikrokosmos — Piezas selectas",
    compositor: "Béla Bartók",
    periodo: "Moderno",
    nivel: "Principiante",
    dificultad: 1,
    descripcion: "Colección pedagógica progresiva de Bartók. Las piezas iniciales son accesibles para cualquier nivel.",
    imslpUrl: "https://imslp.org/wiki/Mikrokosmos_(Bartók,_Béla)",
    anio: "1940",
  },
];
